schema_version: 1

context:
  version: "0.13.1"

package:
  name: shinyswatch
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/shinyswatch/shinyswatch-${{ version }}.tar.gz
  sha256: c453a508728147b39710a551e4c82d83ca596be2a10c9c63fc331cff37a07818

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - typing_extensions >=3.10.0.0
    - packaging >=20.9
    - htmltools >=0.2.0
    - shiny >=1.8.0

tests:
  - python:
      imports:
        - shinyswatch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Bootswatch + Bootstrap 5 themes for Shiny.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rstudio/py-shinyswatch

extra:
  recipe-maintainers:
    - schloerke
